name: Build and Push WalletAnalyser Frontend to Azure

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to WalletAnalyser ACR
        run: |
          az acr login --name walletanalyseracr

      - name: Build Docker image
        run: |
          docker build -t walletanalyseracr.azurecr.io/walletanalyser-frontend:latest .

      - name: Build Docker image
        run: |
          docker build \
            --build-arg VITE_BACKEND_BASE_URL=${{ secrets.VITE_BACKEND_BASE_URL }} \
            --build-arg VITE_GOOGLE_OAUTH_CLIENT_ID=${{ secrets.VITE_GOOGLE_OAUTH_CLIENT_ID }} \
            -t walletanalyseracr.azurecr.io/walletanalyser-frontend:latest .


      - name: Restart Azure App Service
        run: |
          az webapp restart \
            --name app-walletanalyser-frontend \
            --resource-group walletanalyser-rg
